@baseUrl = http://localhost:8080

### Criar um novo cliente
POST {{baseUrl}}/user/
Content-Type: application/json

{
  "name": "Zezinho",
  "password": "secret",
  "confirmPassword": "secret",
  "balance": 100.00,
  "email": "zezinho2@zezinho.com"
} 

### Autenticar usuário
POST {{baseUrl}}/user/auth
Content-Type: application/json

{
  "email": "zezinho2@zezinho.com",
  "password": "secret"
}