@baseUrl = http://localhost:8080
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwYXltZW50LXN5c3RlbSIsInN1YiI6ImYzMjYxMzFkLWE3Y2YtNDUyZC04MmQxLTZhNzE1MDcxZTU1OSIsInJvbGVzIjpbIlVTRVIiXSwiZXhwIjoxNzgyMzUzMzU5fQ.q89M-nBYfwG1gFGxYbP9S1rfQDgMmwnDijBc7lRgN2A
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwYXltZW50LXN5c3RlbSIsInN1YiI6IjI3NjMyZmZhLWFiOTYtNDE4Ni1hYTBlLTIyODhmY2Y4YzRhOSIsInJvbGVzIjpbIlVTRVIiXSwiZXhwIjoxNzgyMzI5NjAwfQ.GXdL9qq5Zv27V7E0jCpXNZtc5DCBelHk0ufVxrA4wBQ
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwYXltZW50LXN5c3RlbSIsInN1YiI6IjI3NjMyZmZhLWFiOTYtNDE4Ni1hYTBlLTIyODhmY2Y4YzRhOSIsInJvbGVzIjpbIlVTRVIiXSwiZXhwIjoxNzgyMzI1OTQyfQ.RtnG2AHWlTq2T3TnDp1zfmp15d_kxSsq53ZA_ZJ7YGQ

### Criar um novo cliente
POST {{baseUrl}}/user/
Content-Type: application/json

{
  "name": "Zezinho",
  "password": "secret",
  "confirmPassword": "secret",
  "balance": 100.00,
  "email": "zezinho@zezinho.com"
} 

### Autenticar usuário
POST {{baseUrl}}/user/auth
Content-Type: application/json

{
  "email": "zezinho@zezinho.com",
  "password": "secret2"
}


### Deletar usuário
DELETE {{baseUrl}}/user/delete
Authorization: Bearer {{authToken}}

### Buscar dados do usuário
GET {{baseUrl}}/user/profile
Authorization: Bearer {{authToken}}

### Trocar senha
PATCH {{baseUrl}}/user/password
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "password": "secret2",
  "confirmPassword": "secret2"
}